kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: presto
  namespace: ersin-test
spec:
  to:
    kind: Service
    name: presto
    weight: 100
  port:
    targetPort: 80-tcp
  wildcardPolicy: None 
