kind: Deployment
apiVersion: apps/v1
metadata:
  name: presto-wo
  namespace: ersin-test
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: presto-wo
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: presto-wo
    spec:
      volumes:
        - name: generic
          persistentVolumeClaim:
            claimName: generic
        - name: empty1
          emptyDir: {}
        - name: presto-catalog-kafka
          configMap:
            name: presto-catalog-kafka
            defaultMode: 511
        - name: presto-catalog-kafka-table
          configMap:
            name: presto-catalog-kafka-table
            defaultMode: 511
        - name: presto-catalog-kafka-work-kpi1
          configMap:
            name: presto-catalog-kafka-work-kpi1
            defaultMode: 511
        - name: presto-catalog-kafka-work-kpi2
          configMap:
            name: presto-catalog-kafka-work-kpi2
            defaultMode: 511
        - name: presto-catalog-kafka-work-kpi3
          configMap:
            name: presto-catalog-kafka-work-kpi3
            defaultMode: 511
        - name: presto-catalog-kafka-work-kpi4
          configMap:
            name: presto-catalog-kafka-work-kpi4
            defaultMode: 511
        - name: presto-catalog-kafka-work-kpi5
          configMap:
            name: presto-catalog-kafka-work-kpi5
            defaultMode: 511
        - name: presto-catalog-kafka-work-kpi6
          configMap:
            name: presto-catalog-kafka-work-kpi6
            defaultMode: 511
        - name: presto-catalog-kafka-work-kpi7
          configMap:
            name: presto-catalog-kafka-work-kpi7
            defaultMode: 511
        - name: presto-config-properties-wo
          configMap:
            name: presto-config-properties-wo
            defaultMode: 511
      containers:
        - name: presto-wo
          image: >-
            starburstdata/presto:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              memory: 2Gi
          volumeMounts:
            - name: presto-catalog-kafka
              mountPath: /usr/lib/presto/etc/catalog/kafka.properties
              subPath: kafka.properties
            - name: presto-catalog-kafka-table
              mountPath: /usr/lib/presto/etc/kafka/turkcell.ersin_table.json
              subPath: turkcell.ersin_table.json
            - name: presto-catalog-kafka-work-kpi1
              mountPath: /usr/lib/presto/etc/kafka/ntc.work_kpi1.json
              subPath: ntc.work_kpi1.json
            - name: presto-catalog-kafka-work-kpi2
              mountPath: /usr/lib/presto/etc/kafka/ntc.work_kpi2.json
              subPath: ntc.work_kpi2.json
            - name: presto-catalog-kafka-work-kpi3
              mountPath: /usr/lib/presto/etc/kafka/ntc.work_kpi3.json
              subPath: ntc.work_kpi3.json
            - name: presto-catalog-kafka-work-kpi4
              mountPath: /usr/lib/presto/etc/kafka/ntc.work_kpi4.json
              subPath: ntc.work_kpi4.json
            - name: presto-catalog-kafka-work-kpi5
              mountPath: /usr/lib/presto/etc/kafka/ntc.work_kpi5.json
              subPath: ntc.work_kpi5.json
            - name: presto-catalog-kafka-work-kpi6
              mountPath: /usr/lib/presto/etc/kafka/ntc.work_kpi6.json
              subPath: ntc.work_kpi6.json
            - name: presto-catalog-kafka-work-kpi7
              mountPath: /usr/lib/presto/etc/kafka/ntc.work_kpi7.json
              subPath: ntc.work_kpi7.json
            - name: presto-config-properties-wo
              mountPath: /usr/lib/presto/etc/config.properties
              subPath: config.properties
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always 
